#!/bin/bash
# Quick setup script for GitHub Actions deployment

echo "════════════════════════════════════════════════════════════════"
echo "  GitHub Actions Deployment Setup - Quick Start"
echo "════════════════════════════════════════════════════════════════"
echo ""

# Step 1: SSH Key
echo "📋 STEP 1: Copy your SSH private key"
echo "────────────────────────────────────────────────────────────────"
echo "Run this command and copy the output:"
echo ""
echo "  cat ~/.ssh/id_ed25519"
echo ""
echo "Then:"
echo "  1. Go to: https://github.com/happyhaplu/outcraftly/settings/secrets/actions"
echo "  2. Click 'New repository secret'"
echo "  3. Name: SERVER_SSH_KEY"
echo "  4. Value: Paste the entire SSH key (including BEGIN/END lines)"
echo "  5. Click 'Add secret'"
echo ""
read -p "Press Enter when done..."

# Step 2: Server IP
echo ""
echo "📋 STEP 2: Add server IP address"
echo "────────────────────────────────────────────────────────────────"
echo "  1. Stay on: https://github.com/happyhaplu/outcraftly/settings/secrets/actions"
echo "  2. Click 'New repository secret'"
echo "  3. Name: SERVER_IP"
echo "  4. Value: 155.133.26.49"
echo "  5. Click 'Add secret'"
echo ""
read -p "Press Enter when done..."

# Step 3: Staging Environment
echo ""
echo "🌍 STEP 3: Create Staging Environment"
echo "────────────────────────────────────────────────────────────────"
echo "  1. Go to: https://github.com/happyhaplu/outcraftly/settings/environments"
echo "  2. Click 'New environment'"
echo "  3. Name: staging"
echo "  4. Click 'Configure environment'"
echo "  5. Environment URL: https://staging.outcraftly.com"
echo "  6. Leave protection rules EMPTY (auto-deploy)"
echo "  7. Click 'Save protection rules'"
echo ""
read -p "Press Enter when done..."

# Step 4: Production Environment
echo ""
echo "🔒 STEP 4: Create Production Environment (with approval)"
echo "────────────────────────────────────────────────────────────────"
echo "  1. Stay on: https://github.com/happyhaplu/outcraftly/settings/environments"
echo "  2. Click 'New environment'"
echo "  3. Name: production"
echo "  4. Click 'Configure environment'"
echo "  5. Environment URL: https://app.outcraftly.com"
echo "  6. ✅ CHECK 'Required reviewers'"
echo "  7. Click 'Add user' and add yourself"
echo "  8. Click 'Save protection rules'"
echo ""
read -p "Press Enter when done..."

# Step 5: Test
echo ""
echo "✅ SETUP COMPLETE!"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "🧪 TEST THE DEPLOYMENT:"
echo ""
echo "1. Make a test commit:"
echo "   git commit --allow-empty -m 'test: deployment workflow'"
echo "   git push origin main"
echo ""
echo "2. Watch deployment:"
echo "   https://github.com/happyhaplu/outcraftly/actions"
echo ""
echo "3. After staging succeeds, merge to production:"
echo "   git checkout release"
echo "   git merge main"
echo "   git push origin release"
echo ""
echo "4. Approve production deployment:"
echo "   Go to Actions tab → Click running workflow"
echo "   → Click 'Review pending deployments'"
echo "   → Check 'production' → Click 'Approve and deploy'"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📚 Full documentation: DEPLOYMENT_GUIDE.md"
echo ""
